baseURL = "https://novumvita.github.io"
theme = 'hugo-bearblog'

title = "renne's ramblings"
author = "renne"
copyright = "Copyright © 2026, Renne."
locale = "en-US"

enableRobotsTXT = false

titleCaseStyle = 'none'

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "renne's ramblings"

# Configure markup highlighter to match "Bearblog" aesthetics, see
# https://gohugo.io/configuration/markup/#highlight
[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

# https://gohugo.io/host-and-deploy/host-on-github-pages/
[caches]
    [caches.images]
    dir = ':cacheDir/images'

[menus]
    [[menus.main]]
        name = 'home'
        pageRef = '/'
        weight = 10
    [[menus.main]]
        name = 'blog'
        pageRef = '/blog'
        weight = 200
